apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: samplexample-ingress
  namespace: web
spec:
  ingressClassName: alb   # Your IngressClass
  defaultBackend:
    service:
      name: samplexample-service
      port:
        number: 80


